### ISSUE TITLE
1.1.8 Distribution of User Features

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#11]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219362723-2af0644c-641e-4204-a1f7-45ef4d8626f0.png)

screenshot of the distribution of user features implemented and to be implemented.

**Comment by LynxYufloria** [comment]
Chosen User features were:
1. CRUD
2. Undo deletion
3. Sorting projects
4. Feedback gathering 
5. feedback Analysis
