### ISSUE TITLE
1.2 Requirements Modelling

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#13]

**Comment by timothxy** [comment]
Completed by everyone in the group.

**Comment by khansharkhamnida** [comment]
This was done to analyze the different perspectives of the system to discuss better with the client as there are many authorities who would be using this system (nurse and manager)

**Comment by YUyou0** [comment]
Helped in identifying, analyzing, and documenting the requirements of the system.
