### ISSUE TITLE
1.2.2 Non-Functional requirements

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#17]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219363233-2ae6fde3-e86a-457b-a80e-05665f61b982.png)

screenshot of the non-functional requirements discussed between the team and the Client.

**Comment by YUyou0** [comment]
Non-Functional requirements between the team and the Client.

![Image](https://user-images.githubusercontent.com/45277234/223389031-fb251433-e3ae-4eed-80d2-cdb4d5fdff53.png)
