### ISSUE TITLE
1.1 Requirements Gathering & Elicitation

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#2]

**Comment by timothxy** [comment]
Completed together as a team.

**Comment by khansharkhamnida** [comment]
For the first meeting (which was done through documents as client was sick), client barely replied to the questions. We decided to rephrase our wordings and got the answers in more details.

**Comment by LynxYufloria** [comment]
Meeting was not that fruitful as client did not answer our questions. It is due to the client being sick and the questions were answered through a document so we could not probe her for answers.

**Comment by YUyou0** [comment]
Craft interview questions to prepare for the client meeting to gather the requirement for the system. Getting feedback from the client regarding the questions asked.
