### ISSUE TITLE
1.6 HouseKeeping & SCMIS prototype

### ISSUE THREAD

**Issue by Uygnis** [LynxYufloria/ICT2106_P3_Project#30]

**Comment by timothxy** [comment]
Completed together as a team.

**Comment by khansharkhamnida** [comment]
Did the prototype in Figma

**Comment by khansharkhamnida** [comment]
https://www.figma.com/file/NDQT96zMJQ2wTZbJknq0Jg/Prototype?node-id=0%3A1&t=nsZFz1ygOs8uGKxO-1

**Comment by YUyou0** [comment]
Completed as a team.
