### ISSUE TITLE
1.4.1 Task Assignment and Timeline

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#37]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219366949-7834182c-22e0-4263-80a2-97ac20e2f127.png)

Screenshot of the task assignment and timeline of the project. Headed by Lin Htoo.

**Comment by LynxYufloria** [comment]
Did up a Gantt Chart from a WBS following the D1 delivariables
