### ISSUE TITLE
1.4.3 Gantt Chart

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#40]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219367304-9b66d2bf-75d7-4f1c-86be-7ff301ef2706.png)

Screenshot of the gantt chart which was worked by WeiQi together with Jansen.

**Comment by YUyou0** [comment]
![Image](https://user-images.githubusercontent.com/45277234/223390711-a6e4bdf4-e266-442b-bd0c-5b8bcf088964.png)
