### ISSUE TITLE
1.1.3 Analysis of 1st Client Interview

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#6]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219362012-9d945b4d-83ad-4656-8eee-ea9e5f88ff30.png)

screenshot of the answers provided by the Client and the group utilising the question to brainstorm any further questions for second interview

**Comment by khansharkhamnida** [comment]
Above are the analysis done by the team
