### ISSUE TITLE
1.1.4 Craft 2nd Interview Questions

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#7]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219350677-6ac65302-6be3-4af4-9da0-27ecf48b953a.png)



![Image](https://user-images.githubusercontent.com/92201555/219350760-ec93b2a2-6b98-495d-a4c4-5c9da94a283d.png)


The set of questions that the group crafted in the second round of the interviews with the Client.
