### ISSUE TITLE
1.1.5 Analysis of 2nd Client Interview

### ISSUE THREAD

**Issue by LynxYufloria** [LynxYufloria/ICT2106_P3_Project#8]

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/219362339-06f5b130-e78d-4af5-9af7-bc734e7c9e2c.png)

screenshot of the answers provided by the Client in the second interview and the group discussing whether there are any further clarifications needed.

**Comment by khansharkhamnida** [comment]
Better answers after rephrasing the questions
